Repository MarlonLira/ProjectH, pull requests merged in 2020-11, with the labels that each got.

#3 feat(Rank): criação da entidade e modelo do Rank
  backend/application/interfaces/point-service.interface.ts
  backend/application/models/rank.model.ts
  backend/application/models/user.model.ts
  backend/domain/entities/rank.entity.ts
  backend/domain/entities/user.entity.ts
  backend/infrastructure/data/context/pst.context.ts
  backend/infrastructure/data/mappings/rank.mapping.ts
  backend/infrastructure/data/mappings/user.mapping.ts
  backend/presentation/config.json
Labels: enhancement

#4 fix(Rank) Correção no mapping do rank
  backend/application/autoMappers/entity-to-model.mapper.ts
  backend/application/autoMappers/model-to-entity.mapper.ts
  backend/application/interfaces/rank-service.interface.ts
  backend/application/models/rank.model.ts
  backend/application/services/rank.service.ts
  backend/domain/entities/rank.entity.ts
  backend/domain/interfaces/rank-repository.interface.ts
  backend/infrastructure/crosscutting/ioc/inversify.config.ts
  backend/infrastructure/crosscutting/ioc/metadata.ts
  backend/infrastructure/crosscutting/ioc/types.ts
  backend/infrastructure/data/mappings/rank.mapping.ts
  backend/infrastructure/data/repositories/rank.repository.ts
  backend/presentation/controllers/category.controller.ts
  backend/presentation/controllers/rank.controller.ts
Labels: bug

#5 Donation
  backend/application/autoMappers/entity-to-model.mapper.ts
  backend/application/autoMappers/model-to-entity.mapper.ts
  backend/application/interfaces/donation-service.interface.ts
  backend/application/interfaces/point-service.interface.ts
  backend/application/models/donation.model.ts
  backend/application/services/donation.service.ts
  backend/application/services/point.service.ts
  backend/domain/entities/donation.entity.ts
  backend/domain/entities/point.entity.ts
  backend/domain/interfaces/donation-repository.interface.ts
  backend/domain/interfaces/point-repository.interface.ts
  backend/infrastructure/crosscutting/ioc/inversify.config.ts
  backend/infrastructure/crosscutting/ioc/metadata.ts
  backend/infrastructure/crosscutting/ioc/types.ts
  backend/infrastructure/data/context/pst.context.ts
  backend/infrastructure/data/mappings/donation.mapping.ts
  backend/infrastructure/data/repositories/donation.repository.ts
  backend/infrastructure/data/repositories/point.repository.ts
  backend/presentation/controllers/donation.controller.ts
  backend/presentation/controllers/point.controller.ts
Labels: enhancement

#6 User
  backend/application/autoMappers/entity-to-model.mapper.ts
  backend/application/commons/core/json.ts
  backend/application/interfaces/user-service.interface.ts
  backend/application/models/user.model.ts
  backend/application/services/log.service.ts
  backend/application/services/user.service.ts
  backend/domain/entities/base.entity.ts
  backend/domain/entities/category.entity.ts
  backend/domain/entities/log.entity.ts
  backend/domain/entities/point.entity.ts
  backend/domain/entities/product.entity.ts
  backend/domain/entities/rank.entity.ts
  backend/domain/entities/user.entity.ts
  backend/domain/interfaces/user-repository.interface.ts
  backend/infrastructure/data/mappings/log.mapping.ts
  backend/infrastructure/data/repositories/user.repository.ts
  backend/presentation/controllers/user.controller.ts
Labels: enhancement

#7 fix(point): correções relacionadas ao point e score do user
  backend/application/models/donation.model.ts
  backend/application/models/point.model.ts
  backend/application/services/point.service.ts
  backend/infrastructure/data/mappings/log.mapping.ts
  backend/infrastructure/data/repositories/user.repository.ts
Labels: bug

#10 initial commit
  mobile/.expo-shared/assets.json
  mobile/.gitignore
  mobile/App.tsx
  mobile/app.json
  mobile/assets/adaptive-icon.png
  mobile/assets/favicon.png
  mobile/assets/icon.png
  mobile/assets/splash.png
  mobile/babel.config.js
  mobile/package-lock.json
  mobile/package.json
  mobile/src/components/Button/index.tsx
  mobile/src/components/ButtonGoBack/index.tsx
  mobile/src/components/Input/index.tsx
  mobile/src/contexts/auth.tsx
  mobile/src/images/Logo.png
  mobile/src/images/avatar.png
  mobile/src/images/logo_red_icon.png
  mobile/src/pages/Donation/index.tsx
  mobile/src/pages/Home/index.tsx
  mobile/src/pages/Login/index.tsx
  mobile/src/pages/Profile/index.tsx
  mobile/src/pages/Progress/index.tsx
  mobile/src/pages/Register/index.tsx
  mobile/src/routes/App.Routes.tsx
  mobile/src/routes/Auth.Routes.tsx
  mobile/src/routes/Routes.tsx
  mobile/src/services/api.ts
  mobile/src/utils/crypto.ts
  mobile/tsconfig.json
  mobile/yarn.lock
Labels: enhancement

#12 fix(donation): ajustes no donation
  backend/application/commons/enums/conditionType.ts
  backend/application/models/donation.model.ts
  backend/application/services/donation.service.ts
  backend/domain/entities/donation.entity.ts
  backend/infrastructure/data/mappings/donation.mapping.ts
  backend/infrastructure/data/repositories/user.repository.ts
Labels: bug

#14 Development
  backend/application/autoMappers/configuration.mapper.ts
  backend/application/autoMappers/entity-to-model.mapper.ts
  backend/application/autoMappers/model-to-entity.mapper.ts
  backend/application/commons/core/json.ts
  backend/application/commons/core/logger.ts
  backend/application/commons/enums/transactionType.ts
  backend/application/interfaces/log-service.interface.ts
  backend/application/models/point.model.ts
  backend/application/models/user.model.ts
  backend/application/services/donation.service.ts
  backend/application/services/log.service.ts
  backend/application/services/point.service.ts
  backend/application/services/product.service.ts
  backend/application/services/rank.service.ts
  backend/application/services/user.service.ts
  backend/domain/entities/user.entity.ts
  backend/infrastructure/crosscutting/ioc/inversify.config.ts
  backend/infrastructure/data/repositories/rank.repository.ts
  backend/package-lock.json
  backend/package.json
Labels: enhancement

#15 Development
  README.md
  backend/application/commons/core/logger.ts
  backend/application/services/donation.service.ts
  backend/application/services/user.service.ts
  backend/infrastructure/data/mappings/log.mapping.ts
  mobile/app.json
  mobile/package-lock.json
  mobile/package.json
  mobile/src/animations/blue.json
  mobile/src/animations/donation.json
  mobile/src/animations/green.json
  mobile/src/animations/pink.json
  mobile/src/animations/red.json
  mobile/src/animations/user.json
  mobile/src/animations/win.json
  mobile/src/animations/yellow.json
  mobile/src/components/CustomProgressBar/index.tsx
  mobile/src/components/Input/index.tsx
  mobile/src/contexts/auth.tsx
  mobile/src/images/logoLarge.png
  mobile/src/pages/Address/index.tsx
  mobile/src/pages/Donation/index.tsx
  mobile/src/pages/Home/index.tsx
  mobile/src/pages/Login/index.tsx
  mobile/src/pages/Profile/index.tsx
  mobile/src/pages/Progress/index.tsx
  mobile/src/pages/Register/index.tsx
  mobile/src/pages/Tokens/index.tsx
  mobile/src/routes/App.Routes.tsx
  mobile/src/routes/Routes.tsx
  mobile/src/services/api.ts
Labels: documentation
